### ISSUE TITLE
Adding more fields to export

### ISSUE THREAD

**Issue by theBREWROOM** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#20]
How do you add more fields to the export file? Specifically, I am trying to add fields that tell me if the entry is paid for or not, as I am using a form as an order form with paypal for payment processing. Any ideas?

**Comment by alexcavender** [comment]
Hi,

Please check out the Dev branch update. It should now work with basically any Field type that Gravity Forms supports. Note that you will want to back-up the form settings that include the scheduled time and email addresses, and will have to re-enter these if you decide to start using the Dev branch version. This version will eventually be merged with the master version at some point since it will clear up many compatibility and export issues

Thanks,
Alex
