### ISSUE TITLE
Enabling automatic export plugin deactivates signature fields

### ISSUE THREAD

**Issue by lusion-jaco** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#3]
There appears to be a clash between your plugin and the signature field on forms, once enabled all existing signature fields disappear :).

**Comment by alexcavender** [comment]
Hi @lusion-jaco 

Thanks for reporting this, I'll be looking into this issue

Alex

**Comment by lusion-jaco** [comment]
Thanks Alex.

I would also like to support your plugin as we have a real need for it. Just doesn't work with the GF Signature Field at the moment.

**Comment by tenebroso** [comment]
+ 1 - Seems to have the same affect on the Coupons add-on, the field itself gets removed when this plugin is activated.

**Comment by Paul7200** [comment]
+2 - Seems to also affect [Survey](http://www.gravityforms.com/add-ons/survey/) add-on, the fields also removed when this plugin activated.

**Comment by alexcavender** [comment]
Hi,

If you want to check out the Dev branch update, I'm working on some broader compatibility changes. For some reason accessing basic GForms API stuff was interfering with the Survey plugin but I think I have fixed it. **Please keep in mind if you do decide update to the Dev branch version, you will want to first back up the scheduled times and emails for each field, and will have to re-enter these.**

I'm going to close this for now, since from what I can see with my testing it is now resolved with other major Gforms add-ons
Thanks
